### ISSUE TITLE
plugin.js?t=H0CG:4915 Uncaught TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by impushkar** [anishmprasad/ckeditor_wiris#2]
![2019-05-24-130218_1366x768_scrot](https://user-images.githubusercontent.com/32325817/58310409-3125e400-7e24-11e9-8e3f-dbf89dcd015b.png)

**Comment by anishmprasad** [comment]
give me more details with code snippet

prefer codesandbox for preview
